# Generated by Django 5.2 on 2025-04-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Flavor Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Small, Medium, 8-inch', max_length=50, unique=True, verbose_name='Size Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimated Weight (kg)')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cake Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cakes/', verbose_name='Image')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('PER_KG', 'Price Per Kg')], default='FIXED', max_length=10, verbose_name='Price Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='products.category', verbose_name='Category')),
                ('available_flavors', models.ManyToManyField(blank=True, related_name='cakes', to='products.flavor', verbose_name='Available Flavors')),
                ('available_sizes', models.ManyToManyField(blank=True, related_name='cakes', to='products.size', verbose_name='Available Sizes')),
            ],
            options={
                'verbose_name': 'Cake',
                'verbose_name_plural': 'Cakes',
                'ordering': ['name'],
            },
        ),
    ]
