# Generated by Django 5.2 on 2025-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Addon Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Leave blank if stock is not tracked', null=True, verbose_name='Stock')),
                ('category', models.CharField(blank=True, choices=[('DECOR', 'Decorations'), ('CANDLE', 'Candles'), ('CARD', 'Greeting Cards'), ('UTENSIL', 'Utensils'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
                'ordering': ['name'],
            },
        ),
    ]
