# Generated by Django 5.2 on 2025-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, help_text='A URL-friendly version of the category name, usually auto-generated.', max_length=120, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
