# Generated by Django 5.2 on 2025-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='slug',
            field=models.SlugField(default=1, help_text='A URL-friendly version of the cake name, auto-generated if left blank.', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
