# Generated by Django 5.2 on 2025-05-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cake_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='allergen_info_text',
            field=models.TextField(blank=True, null=True, verbose_name='Allergen Info Text'),
        ),
        migrations.AddField(
            model_name='cake',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='cake',
            name='ingredients_text',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients Text'),
        ),
        migrations.AddField(
            model_name='cake',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this cake in featured sections?', verbose_name='Is Featured'),
        ),
        migrations.AddField(
            model_name='cake',
            name='nutrition_info_text',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition Info Text'),
        ),
        migrations.AddField(
            model_name='cake',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Review Count'),
        ),
        migrations.AddField(
            model_name='size',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='مبلغی که به قیمت پایه کیک برای این سایز اضافه یا کم می\u200cشود (می\u200cتواند منفی باشد).', max_digits=10, verbose_name='Price Modifier'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cakes/gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.cake', verbose_name='Cake')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['cake', 'id'],
            },
        ),
    ]
