# Generated by Django 5.2 on 2025-05-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this category currently active and visible?', verbose_name='Is Active'),
        ),
    ]
