# Generated by Django 5.2 on 2025-05-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
