# Generated by Django 5.2 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_size_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sale End Date'),
        ),
        migrations.AddField(
            model_name='cake',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='cake',
            name='sale_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sale Start Date'),
        ),
        migrations.AddField(
            model_name='cake',
            name='schedule_sale_enabled',
            field=models.BooleanField(default=False, verbose_name='Schedule Sale Enabled'),
        ),
    ]
