# Generated by Django 5.2 on 2025-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cake_sale_end_date_cake_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Short Description'),
        ),
    ]
