# Generated by Django 5.2 on 2025-06-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cake_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='مبلغی که به قیمت پایه کیک برای این ترکیب اندازه اضافه یا از آن کم می\u200cشود.', max_digits=10, verbose_name='Price Modifier for this Variant')),
                ('estimated_weight_kg_override', models.DecimalField(blank=True, decimal_places=2, help_text='وزن دقیق این محصول با این اندازه، اگر با وزن پیش\u200cفرض اندازه متفاوت است.', max_digits=5, null=True, verbose_name='Specific Weight for this Variant (kg)')),
                ('sku_variant', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU for Variant')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Quantity for Variant')),
                ('is_active_for_product', models.BooleanField(default=True, verbose_name='Is this variant active for product')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants_through', to='products.cake')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_variants_through', to='products.size')),
            ],
            options={
                'verbose_name': 'Cake Size Variant',
                'verbose_name_plural': 'Cake Size Variants',
                'unique_together': {('cake', 'size')},
            },
        ),
        migrations.AlterField(
            model_name='cake',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='cakes', through='products.CakeSizeVariant', to='products.size'),
        ),
    ]
