# Generated by Django 5.2 on 2025-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='meta_description',
            field=models.TextField(blank=True, help_text='توضیحات مختصر (حدود ۱۶۰ کاراکتر) برای نمایش در نتایج گوگل.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='cake',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='کلمات کلیدی مرتبط با محصول، جدا شده با کاما (,). (اهمیت کمتری برای سئوی مدرن دارد)', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='cake',
            name='meta_title',
            field=models.CharField(blank=True, help_text='عنوان سئو برای نمایش در تب مرورگر و نتایج گوگل. اگر خالی باشد، از نام محصول استفاده می\u200cشود.', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='cake',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cakes', to='products.tag'),
        ),
    ]
