# Generated by Django 5.2 on 2025-06-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag_cake_meta_description_cake_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakesizevariant',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.cake'),
        ),
        migrations.AlterField(
            model_name='cakesizevariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_variants', to='products.size'),
        ),
    ]
