# Generated by Django 5.2 on 2025-06-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cakes', to='products.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
