# Generated by Django 5.2 on 2025-08-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Color Name')),
                ('hex_code', models.CharField(help_text='e.g., #FFFFFF', max_length=7, verbose_name='Hex Code')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type Name')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Theme Name')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Supply Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='برای آدرس URL محصول', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplies/', verbose_name='Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('colors', models.ManyToManyField(blank=True, related_name='supplies', to='products.color', verbose_name='Colors')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='products.supplytype', verbose_name='Product Type')),
                ('themes', models.ManyToManyField(blank=True, related_name='supplies', to='products.theme', verbose_name='Themes')),
            ],
            options={
                'verbose_name': 'Party Supply',
                'verbose_name_plural': 'Party Supplies',
                'ordering': ['name'],
            },
        ),
    ]
