# Generated by Django 5.2 on 2025-04-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.address', verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, help_text='Chosen date and start time slot for delivery', null=True, verbose_name='Delivery Date/Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('CART', 'Cart')], db_index=True, default='CART', max_length=20, verbose_name='Status'),
        ),
    ]
