# Generated by Django 5.2 on 2025-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_alter_order_delivery_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Customization Notes'),
        ),
    ]
