# Generated by Django 5.2 on 2025-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Tracking Code (RefID)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('CART', 'Cart'), ('PAYMENT_FAILED', 'Payment Failed')], db_index=True, default='CART', max_length=20, verbose_name='Status'),
        ),
    ]
