# Generated by Django 5.2 on 2025-05-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_transaction_ref_id_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_trigger', models.CharField(choices=[('ORDER_CONFIRMED', 'تایید سفارش (پس از پرداخت)'), ('ORDER_PROCESSING', 'سفارش در حال پردازش'), ('ORDER_SHIPPED', 'سفارش ارسال شده'), ('ORDER_DELIVERED', 'سفارش تحویل داده شده'), ('ORDER_CANCELLED', 'سفارش لغو شده')], max_length=50, unique=True, verbose_name='رویداد/وضعیت سفارش محرک')),
                ('message_template', models.TextField(help_text='از متغیرهایی مانند {{customer_name}}, {{order_id}}, {{order_total}}, {{tracking_number}}, {{store_name}} استفاده کنید.', verbose_name='متن قالب پیامک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای ارسال')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات قالب')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
            },
        ),
    ]
