# Generated by Django 5.2 on 2025-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_smstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='notification',
            name='gateway_message_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='Gateway Message IDs'),
        ),
        migrations.AddField(
            model_name='notification',
            name='gateway_pack_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Pack ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='gateway_response_message',
            field=models.TextField(blank=True, null=True, verbose_name='Gateway Response Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='gateway_response_status_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gateway Status Code'),
        ),
    ]
