# Generated by Django 5.2 on 2025-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_notification_cost_notification_gateway_message_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ['event_trigger'], 'verbose_name': 'SMS Template', 'verbose_name_plural': 'SMS Templates'},
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Code'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template Description'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='event_trigger',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ORDER_CONFIRMED', 'Order Confirmed (after payment)'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('PAYMENT_FAILED', 'Payment Failed')], max_length=50, unique=True, verbose_name='Order Status Trigger Event'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active for Sending'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='message_template',
            field=models.TextField(help_text='Use placeholders like {{customer_name}}, {{order_id}}, {{order_total}}, {{tracking_number}}, {{store_name}}.', verbose_name='SMS Template Text (with placeholders)'),
        ),
    ]
