# Generated by Django 5.2 on 2025-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_smstemplate_options_order_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='علامت\u200cگذاری سفارش به عنوان حذف شده به جای حذف فیزیکی', verbose_name='Is Deleted'),
        ),
    ]
