# Generated by Django 5.2 on 2025-05-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('PICKUP', 'تحویل حضوری'), ('PEYK', 'پیک موتوری'), ('POST', 'پست پیشتاز')], max_length=50, null=True, verbose_name='Shipping Method'),
        ),
    ]
