"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv() # loads variables from .env file   



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # BASE_DIR معمولاً در بالای settings.py تعریف شده

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)+yibapd=)t6y3xv=jfkqb^$28nr!@=sp!7ah0ud15rs2-w+c&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173') # آدرس فرانت‌اند (React) شما با Vite

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',

    # Third-party apps
    'rest_framework',
    'corsheaders', # اضافه شد
    'rest_framework_simplejwt', 
    # Your apps
    'users',
    'products',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <--- اضافه شد در اینجا
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': os.environ.get('DATABASE_NAME'),
                    'USER': os.environ.get('DATABASE_USER'),
                    'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
                    'HOST': os.environ.get('DATABASE_HOST'),
                    'PORT': os.environ.get('DATABASE_PORT', '5432'), # Provide default port
                }
            }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True # برای توسعه - به همه اجازه می‌دهد

# یا برای امنیت بیشتر حتی در توسعه (پورت پیش‌فرض React)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000", # آدرس سرور توسعه React شما
#     "http://127.0.0.1:3000",
# ]

# در Production باید لیست دامنه‌های مجاز فرانت‌اند رو مشخص کنید:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # آدرس فرانت‌اند React شما با Vite
    "http://127.0.0.1:5173", # گاهی این هم لازم است
    # در صورت نیاز آدرس‌های دیگر (مثل آدرس دیپلوی شده) را هم اضافه کنید
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # اولویت با JWT هست
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # SessionAuthentication رو هم نگه می‌داریم تا همچنان بتونیم از
        # Browsable API با لاگین ادمین برای تست‌های ساده GET استفاده کنیم.
        # اگر می‌خواید API فقط با توکن کار کنه، این خط رو حذف کنید.
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # سطح دسترسی پیش‌فرض (مثلاً همه باید لاگین باشن، مگر اینکه در View خاصی لغو بشه)
        'rest_framework.permissions.IsAuthenticated',
        # یا 'rest_framework.permissions.IsAuthenticatedOrReadOnly' اگر درخواست‌های GET عمومی باشن
    )
    # تنظیمات دیگری هم می‌تونید اینجا اضافه کنید (مثل Pagination, Throttling)
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # مثال: توکن دسترسی ۱۵ دقیقه معتبر باشد
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # مثال: توکن بازنشانی ۷ روز معتبر باشد
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',), # باید Bearer باشد
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

ZARINPAL_MERCHANT_ID = os.environ.get('ZARINPAL_MERCHANT_ID') # خواندن از .env
DEBUG = True 

# تنظیمات اصلی sms.ir
SMS_IR_API_KEY_PRODUCTION = os.environ.get('SMS_IR_API_KEY_PRODUCTION') # کلید اصلی شما
SMS_IR_LINE_NUMBER = os.environ.get('SMS_IR_LINE_NUMBER')
SMS_IR_API_BASE_URL = os.environ.get('SMS_IR_API_BASE_URL', 'https://api.sms.ir/v1/') # URL پایه اصلی

# تنظیمات Sandbox sms.ir
SMS_IR_API_KEY_SANDBOX = os.environ.get('SMS_IR_API_KEY_SANDBOX') # کلید Sandbox شما
# URL پایه برای Sandbox معمولاً همان URL پایه اصلی است، اما اگر متفاوت بود، اینجا تعریف کنید.
# SMS_IR_API_BASE_URL_SANDBOX = os.environ.get('SMS_IR_API_BASE_URL_SANDBOX', 'https://api.sms.ir/v1/')


# یک متغیر برای تعیین اینکه آیا در حالت Sandbox هستیم یا خیر
# این می‌تواند بر اساس DEBUG یا یک متغیر محیطی دیگر تنظیم شود
USE_SMS_IR_SANDBOX = os.environ.get('USE_SMS_IR_SANDBOX', 'False').lower() == 'true'
# یا اگر می‌خواهید همیشه در حالت DEBUG از Sandbox استفاده کنید:
# USE_SMS_IR_SANDBOX = DEBUG

if DEBUG:
    # آدرس‌های سندباکس (از مستندات زرین‌پال بگیرید)
    ZARINPAL_REQUEST_URL = "https://sandbox.zarinpal.com/pg/v4/payment/request.json"
    ZARINPAL_VERIFY_URL = "https://sandbox.zarinpal.com/pg/v4/payment/verify.json"
    ZARINPAL_STARTPAY_URL = "https://sandbox.zarinpal.com/pg/StartPay/"
    print("--- Using Zarinpal SANDBOX URLs ---")
else:
    # آدرس‌های اصلی زرین‌پال (از مستندات زرین‌پال بگیرید)
    ZARINPAL_REQUEST_URL = "https://api.zarinpal.com/pg/v4/payment/request.json"
    ZARINPAL_VERIFY_URL = "https://api.zarinpal.com/pg/v4/payment/verify.json"
    ZARINPAL_STARTPAY_URL = "https://www.zarinpal.com/pg/StartPay/"

SITE_NAME = "BAKEJOY"