# Generated by Django 5.2 on 2025-06-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_size_orderitem_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, help_text='Unique order number with prefix.', max_length=20, null=True, verbose_name='Order Number'),
        ),
    ]
