# Generated by Django 5.2 on 2025-08-09 11:03

from django.db import migrations

def forwards_populate_content_object(apps, schema_editor):
    """
    داده‌ها را از فیلد قدیمی cake به فیلدهای GenericForeignKey منتقل می‌کند.
    """
    OrderItem = apps.get_model('orders', 'OrderItem')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Cake = apps.get_model('products', 'Cake')

    # ContentType مربوط به مدل Cake را پیدا کن
    cake_content_type = ContentType.objects.get_for_model(Cake)

    # تمام آیتم‌هایی که هنوز فیلد content_type ندارند را آپدیت کن
    for item in OrderItem.objects.filter(content_type__isnull=True, cake__isnull=False):
        item.content_type = cake_content_type
        item.object_id = item.cake_id
        item.save(update_fields=['content_type', 'object_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_options_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_populate_content_object),

    ]
