# Generated by Django 5.2 on 2025-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_city_province_alter_address_city_city_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(default='', max_length=150, verbose_name='Recipient Name'),
            preserve_default=False,
        ),
    ]
