# Generated by Django 5.2 on 2025-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_populate_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
